# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x12org.investpro.grpc\x1a\x1bgoogle/protobuf/empty.proto\"\xb6\x01\n\x11MarketDataRequest\x12\x0c\n\x04open\x18\x01 \x01(\x01\x12\r\n\x05\x63lose\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\x0e\n\x06volume\x18\x05 \x01(\x01\x12\x0b\n\x03rsi\x18\x06 \x01(\x01\x12\x0b\n\x03\x61tr\x18\x07 \x01(\x01\x12\x0c\n\x04macd\x18\x08 \x01(\x01\x12\r\n\x05stoch\x18\t \x01(\x01\x12\x10\n\x08\x62\x62_upper\x18\n \x01(\x01\x12\x10\n\x08\x62\x62_lower\x18\x0b \x01(\x01\"<\n\x12PredictionResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\"\x1e\n\x0cHealthStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2\xae\x01\n\tPredictor\x12X\n\x07Predict\x12%.org.investpro.grpc.MarketDataRequest\x1a&.org.investpro.grpc.PredictionResponse\x12G\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a .org.investpro.grpc.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETDATAREQUEST']._serialized_start=67
  _globals['_MARKETDATAREQUEST']._serialized_end=249
  _globals['_PREDICTIONRESPONSE']._serialized_start=251
  _globals['_PREDICTIONRESPONSE']._serialized_end=311
  _globals['_HEALTHSTATUS']._serialized_start=313
  _globals['_HEALTHSTATUS']._serialized_end=343
  _globals['_PREDICTOR']._serialized_start=346
  _globals['_PREDICTOR']._serialized_end=520
# @@protoc_insertion_point(module_scope)
